### ISSUE TITLE
Ideia: Criar uma função de banir membros com DDI +1 ao entrar no grupo via link de convite.

### ISSUE THREAD

**Issue by HoaxBR** [MuriloucoLouco/whatsapp-bot#1]
Base para fazer (peguei pelos fóruns adentro)
const metaDataGroup = Store.GroupMetadata.get(idGroup);
const participant = metaDataGroup.participants.get(idParticipant);
metaDataGroup.participants.removeParticipants([participant]).then((ret)=>{ const check = metaDataGroup.participants.get(idParticipant); if (check === undefined){ done(true); return true; } done(false); return false; })

idGroup '0000000000-00000000@g.us'
idParticipant '000000000000@c.us'

Boa sorte, eu tentei aqui, mas ainda to aprendendo a fazer, então não rolou. Espero que consiga haha <3

**Comment by MuriloucoLouco** [comment]
Parece uma boa ideia (apesar de ser difícil fazer os testes por eu não ter pessoas com número DDI 1). Vou definir algumas metas para isso, imagino que a última etapa será bem fácil. Vou atualizar aqui a medida que for completando.

- [x] Criar função de banir usuário.
- [x] Criar listener de novos usuários.
- [x] Checar se o número tem DDI 1.

Enfim, não esperava que alguém fosse descobrir esse projeto, criei ele como brincadeira entre amigos. Obrigado pelo suporte!

**Comment by HoaxBR** [comment]
Criei este número +1 567 305-7642
Pode usar para os testes!

**Comment by MuriloucoLouco** [comment]
Excelente! Vou adicionar aqui, muito obrigado.

**Comment by MuriloucoLouco** [comment]
Adicionei todas as funções. Se quiser remover esse sistema de ban, modifique o `src/start_bot.js`.
