### ISSUE TITLE
trocar api do whatsapp web

### ISSUE THREAD

**Issue by leonimeloo** [MuriloucoLouco/whatsapp-bot#3]
Você poderia mudar seu código para trocar a API do Whatsapp Web? Daria para usar [WA AUTOMATE](https://github.com/open-wa/wa-automate-nodejs) ou [BAILEYS](https://github.com/adiwajshing/Baileys)

**Comment by MuriloucoLouco** [comment]
Esse código é em geral para eu treinar programação, em especial as Web APIs do javascript. Não planejo trocar a API para uma melhor e mais fácil por conta disso, apesar de que eu posso um dia colocar as duas ao mesmo tempo, de forma opcional no config.json.
